# mysql
Host: localhost:3306
User: root
Password: 141097
DbName: mall

# redis
RedisAddr: 43.142.93.115:6379
RedisPass: 141097
DB: 0
PoolSize: 20

# 阿里云
#Endpoint: https://oss-cn-qingdao.aliyuncs.com
Endpoint: oss-cn-qingdao.aliyuncs.com
AccessKeyId: LTAI5tHU5a9g4yuJzoSNjwKM
AccessKeySecret: wyxSSSOmhoxuqcY2CiD3pITJPZ2yjC
BucketName: gin-mall